/* tslint:disable */
/* eslint-disable */
/**
 * Chatter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPayload
 */
export interface AuthLoginPayload {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPayload
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPayload
     */
    password: string;
}

export function AuthLoginPayloadFromJSON(json: any): AuthLoginPayload {
    return AuthLoginPayloadFromJSONTyped(json, false);
}

export function AuthLoginPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthLoginPayloadToJSON(value?: AuthLoginPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}


