/* tslint:disable */
/* eslint-disable */
/**
 * Chatter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AuthLoginPayload,
    AuthLoginPayloadFromJSON,
    AuthLoginPayloadFromJSONTyped,
    AuthLoginPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    provider: InlineObjectProviderEnum;
    /**
     * 
     * @type {AuthLoginPayload}
     * @memberof InlineObject
     */
    payload: AuthLoginPayload;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'payload': AuthLoginPayloadFromJSON(json['payload']),
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
        'payload': AuthLoginPayloadToJSON(value.payload),
    };
}

/**
* @export
* @enum {string}
*/
export enum InlineObjectProviderEnum {
    Email = 'email',
    Apple = 'apple',
    Google = 'google',
    Twitter = 'twitter',
    Facebook = 'facebook'
}


